### ISSUE TITLE
umaal instruction

### ISSUE THREAD

**Issue by pftbest** [rust-lang-nursery/compiler-builtins#112]
So I was playing with compiler-builtins-snapshot in qemu, and my program was hanging for no apparent reason. Then I looked into the code that was causing problems and found this instruction:
```
0x3c8a <core::num::flt2dec::strategy::grisu::format_shortest_opt+652>   umaal  r1, r5, r2, r3
```
This instruction should not be used on thumbv7m-none-eabi target.

**Comment by japaric** [comment]
> umaal

This is a Cortex-M4 or newer instruction and shouldn't be generated by the thumbv7m target.

Do you have steps to reproduce? This sounds like the built-in thumbv7m target could be missing a "negative" LLVM feature. Are you passing any extra compiler flag related to codegen, like `-C cpu=`? Are you linking to C code?

**Comment by pftbest** [comment]
you can compile the code in question, it is on https://github.com/pftbest/rplayground

**Comment by japaric** [comment]
The instruction doesn't seem to come from compiler-builtins-snapshot AFAICT:

```
$ cargo clone compiler-builtins-snapshot && cd $_

$ xargo build --target thumbv7m-none-eabi

$ arm-none-eabi-objdump -CD target/thumbv7m-none-eabi/debug/libcompiler_builtins_snapshot.rlib | grep uma || echo no matches
no matches

$ xargo build --target thumbv7m-none-eabi --release

$ arm-none-eabi-objdump -CD target/thumbv7m-none-eabi/release/libcompiler_builtins_snapshot.rlib | grep uma || echo no matches
no matches
```

**Comment by japaric** [comment]
I see you have two .json files in your project. Could you, by mistake, by using the `stm32f429zi` target with QEMU instead of the `qemu` target? The former is a thumbv7em target and its binaries would have the umaal instruction.

**Comment by pftbest** [comment]
>Could you, by mistake by using the stm32f429zi

no, it is commented out in the `Makefile`, I always use `make clean` `make all` and `make run` to build and run the project.

>The instruction doesn't seem to come from compiler-builtins-snapshot

This may be the case, I'm not sure where it comes from, maybe it is from libcore, as is suggested by the `core::num::flt2dec::strategy::grisu::format_shortest_opt` prefix

**Comment by japaric** [comment]
Yes, they are coming from libcore. This is a bug in the target definition and should be fixed upstream, in rust-lang/rust.

**Comment by japaric** [comment]
Filed rust-lang/rust#37227

**Comment by pftbest** [comment]
Thank you
