### ISSUE TITLE
Can't publish my crate to crates.io if it depends on compiler-builtins

### ISSUE THREAD

**Issue by thejpster** [rust-lang-nursery/compiler-builtins#134]
I get this error trying to publish my crate

```
$ rustup run nightly cargo publish
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: all dependencies must come from the same source.
dependency `compiler_builtins` comes from https://github.com/rust-lang-nursery/compiler-builtins.git instead
```

The snapshot on crates.io has a different name, and doesn't have the "mem" feature (so I suspect it is old). Is there a plan to move this onto crates.io, or can we update the snapshot?

Thanks.

**Comment by japaric** [comment]
> The snapshot on crates.io has a different name, and doesn't have the "mem" feature

There's a `memcpy` feature in that snapshot but it doesn't work as well as the `mem` feature in this repository.

> Is there a plan to move this onto crates.io

No, I don't think so. But once this lands in rust-lang/rust, you'll be able to use it by specifying this crate as a dependency in Xargo.toml

> or can we update the snapshot?

I'll update the snapshot ASAP.

**Comment by thejpster** [comment]
Excellent, that works for me.

I've got a third-party user for launchpad-rs (and my embedded-serial
crate), but this was blocking getting it on crates.io, so thanks for the
very prompt response.

I continue to be really impressed by this community. *high five*

**Comment by japaric** [comment]
@thejpster release a new 0.1.* version with the mem feature.

**Comment by thejpster** [comment]
https://crates.io/crates/stellaris-launchpad - works great.
