### ISSUE TITLE
Segfault in __udivmodti4 quickcheck when remainder is requested

### ISSUE THREAD

**Issue by est31** [rust-lang-nursery/compiler-builtins#137]
PR #133 adds quickcheck tests for `__udivmodti4` with the code that does checking with remainder enabled commented out. I commented it out as I got a segfault.

**Comment by est31** [comment]
The segfault happens at:

```
0x00007ffff55fc22e in __udivmodti4 (a=11837846198047054611, b=10468428215946443262, rem=0x7ffff67fc388)
    at compiler-rt/lib/builtins/udivmodti4.c:47
47                      *rem = n.s.low % d.s.low;
```

**Comment by japaric** [comment]
According to [this Travis build](https://travis-ci.org/rust-lang-nursery/compiler-builtins/builds/220750542), this appears to only happens on MIPS.

**Comment by est31** [comment]
@japaric as you can see from this travis log, it failed on multiple 64 bit platforms (x86_64, aarch64, mips64, powerpc64, ...): https://travis-ci.org/rust-lang-nursery/compiler-builtins/builds/198218713

**Comment by japaric** [comment]
@est31 AFAICS, all the errors in the build you have linked seem to be due to "missing symbol" which indicates a bad cache.

**Comment by est31** [comment]
@japaric ah you are right. I *think* I remember though reproducing the issue on my native platform (x86_64). Maybe you can try to comment out [this code](https://github.com/rust-lang-nursery/compiler-builtins/blob/9aa3a257d61ed51d5a38360b2aa37e1c571d594b/src/int/udiv.rs#L423-L426) and try whether you can reproduce?

**Comment by japaric** [comment]
> Maybe you can try to comment out this code and try whether you can reproduce?

I can  locally repro on x86_64. The weird thing is that we are not hitting this bug on x86_64 and other arches in #155.
