### ISSUE TITLE
mulodi4 debug assertion

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/compiler-builtins#148]
### STR

``` rust
#![feature(compiler_builtins_lib)]

extern crate compiler_builtins;

use compiler_builtins::int::mul::__mulodi4;

fn main() {
    let (a, b) = (72113192, -480093263);
    let mut overflow = 2;
    let c = __mulodi4(a, b, &mut overflow);
}
```

```
$ cross run --target armv7-unknown-linux-gnueabihf
     Running `/target/armv7-unknown-linux-gnueabihf/debug/foo`
thread 'main' panicked at 'attempt to subtract with overflow', /cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/0507842/src/int/sdiv.rs:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The command hangs and doesn't return but that could be a Cross bug ... I don't know.

**Comment by japaric** [comment]
The problem actually originates from:

``` rust
__divdi3(72113192, -480093263)
```

**Comment by oli-obk** [comment]
can you publish a new snapshot that includes this fix?

**Comment by japaric** [comment]
@oli-obk that snapshot crate was a hack. The compiler-builtins crate truly belongs in the sysroot; it's just that the rust-lang/rust version of that crate has too few intrinsics so I decided to directly depend on this crate (because I didn't want to use the C implementations of the intrinsics).

Xargo has been capable of putting custom crates in the sysroot for a while and this crate is now "thumb friendly" due to recent changes. I suggest that you remove the direct dependency to compiler-builtins from your dependency graph and instead build it as part of the Xargo sysroot. [Example](https://github.com/japaric/cortex-m-quickstart/commit/127c26584ef09a3aa8c0e52a3064d2f25610cc66#diff-73320d2d67728eb6e932b7cd575a2ec7)

If you want to continue using the snapshot crate, I'd be happy to transfer ownership of it to you so you can update / maintain it.
