### ISSUE TITLE
Can't built against snapshot

### ISSUE THREAD

**Issue by thejpster** [rust-lang-nursery/compiler-builtins#163]
Is the snapshot on crates.io out of date again? I did a build today (for the first time in a while) and I get a lot of "This node does not have a stability attribute" errors. This, unfortunately, breaks my crates on crates.io.

See https://travis-ci.org/thejpster/stellaris-launchpad/builds/232592732

**Comment by thejpster** [comment]
I can confirm that building with latest git (and adding `#![feature(compiler_builtins_lib)]`) works.

**Comment by japaric** [comment]
I'm no longer maintaining that crate as it was a hack. See explanation [here](https://github.com/rust-lang-nursery/compiler-builtins/issues/148#issuecomment-293446692). You should use a Xargo.toml to provide that crate.

**Comment by thejpster** [comment]
OK, thanks. That gives different issues, but this one can be closed.
