### ISSUE TITLE
Whitelist undefined symbols?

### ISSUE THREAD

**Issue by TimNN** [rust-lang-nursery/compiler-builtins#182]
In https://github.com/rust-lang-nursery/compiler-builtins/pull/181#issuecomment-317229561, @alexcrichton asked:

> I wonder if it'd be possible to add a test for this [compiler-builtins (not) depending on memcpy] as well?

I think the issue is a bit more general, in that we should check that only a known list of symbols is undefined, this can be done (on x86_64 linux) like this:

``` sh
$ mkdir tmp && cd tmp
$ ar x $DIR/libcompiler_builtins-614d629936883e62.rlib
$ ld -r -o tmp.o *.o
$ nm -u tmp.o
```

The output (before #181) looks something like this:

```
                 U abort
                 U fmax
                 U fmaxf
                 U fmaxl
                 U _GLOBAL_OFFSET_TABLE_
                 U logb
                 U logbf
                 U logbl
                 U memcpy
                 U rust_eh_personality
                 U scalbn
                 U scalbnf
                 U scalbnl
                 U _Unwind_Resume
                 U _ZN4core9panicking9panic_old17hd5ed84fef9dfdb68E
```

**Comment by alexcrichton** [comment]
I'm gonna close this for now since it's quite old and I think we've learned that a list like this in CI would be pretty difficult to maintain over time, but for now it's not a super pressing problem so I think we're largely ok
