### ISSUE TITLE
Example build fails

### ISSUE THREAD

**Issue by richdrich** [rust-lang-nursery/compiler-builtins#185]
Commit:  94c4c1c5
    rustup show
    Default host: x86_64-unknown-linux-gnu

    nightly-x86_64-unknown-linux-gnu (default)
    rustc 1.21.0-nightly (e26688824 2017-08-27)

`cargo run --example intrinsics --features="c compiler-builtins"`

gives

    cargo:warning=cc: error: ./compiler-rt/lib/builtins/absvdi2.c: No such file or directory
    cargo:warning=cc: fatal error: no input files
    cargo:warning=compilation terminated.

Full log attached.
[example_fail.txt](https://github.com/rust-lang-nursery/compiler-builtins/files/1262967/example_fail.txt)

**Comment by mattico** [comment]
Did you update the git submodules? `git submodule update --init --recursive`

**Comment by richdrich** [comment]
I did now. Thank you, that worked (at least for the non-cross compile case)

**Comment by mattico** [comment]
It's probably worth mentioning that in the readme.

**Comment by alexcrichton** [comment]
I believe this isn't a bug with this repository so closing.
