### ISSUE TITLE
Submodules make this repository prohibitively large

### ISSUE THREAD

**Issue by whitequark** [rust-lang-nursery/compiler-builtins#186]
Not everyone has unmetered 100 Mbps internet connection. The compiler-rt submodule is something like 25 MB in size, and pulling it in over a mobile connection, the only that's currently available to me, takes something like ten minutes. Combined with the fact that Cargo does not seem to cache submodules, it makes using this crate a miserable experience.

**Comment by japaric** [comment]
Not a solution for this issue but, depending on what you want to do, you can find a snapshot of this repo, along with its compiler-rt submodule, in the `rust-src` component which can be installed using rustup (`rustup component add rust-src`) and which "only" weights 2.5 MB, 10% of the size you have mentioned.

**Comment by whitequark** [comment]
I'm trying to use it as a Cargo dependency.

**Comment by alexcrichton** [comment]
This isn't something we're going to fix, so closing.

**Comment by whitequark** [comment]
@alexcrichton  Is everyone using this crate expected to have unmetered broadband?
