### ISSUE TITLE
Current version of compiler-rt is incompatible with glibc 2.26

### ISSUE THREAD

**Issue by Keruspe** [rust-lang-nursery/compiler-builtins#190]
I'm hitting this rust build failure with sanitizers enabled: https://github.com/rust-lang/rust/issues/44421

It seems that newer compiler-rt support that just fine. Could the submodule be updated?

**Comment by mattico** [comment]
The submodule [is waiting](https://github.com/rust-lang-nursery/compiler-builtins/pull/180) to be updated along with the [rest of llvm 5.0](https://github.com/rust-lang/rust/issues/43370). I think.

**Comment by cuviper** [comment]
See also: https://bugs.llvm.org/show_bug.cgi?id=34719

**Comment by ishitatsuyuki** [comment]
xpost: https://github.com/rust-lang/rust/issues/43370#issuecomment-334977186

This is a blocker for building on Arch.
