### ISSUE TITLE
Missing 128-bit integer functions on aarch64

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang-nursery/compiler-builtins#213]
I'm seeing the following undefined references when compiling a bare-metal `aarch64` program:

```
In function `core::num::from_str_radix': undefined reference to `__udivti3'
In function `core::num::from_str_radix': undefined reference to `__muloti4'
In function `core::num::<impl core::str::FromStr for u128>::from_str': undefined reference to `__udivti3'
In function `core::fmt::num::<impl core::fmt::Debug for i128>::fmt': undefined reference to `__umodti3'
In function `core::fmt::num::<impl core::fmt::Debug for u128>::fmt': undefined reference to `__umodti3'
In function `core::fmt::num::<impl core::fmt::Display for i128>::fmt': undefined reference to `__umodti3'
In function `core::fmt::num::<impl core::fmt::Display for u128>::fmt': undefined reference to `__umodti3'
```

In particular, `__udivti3`, `__muloti4`, and `__umodti3` are missing. These are all 128-bit integer functions.

**Comment by japaric** [comment]
> In particular, __udivti3, __muloti4, and __umodti3 are missing.

All those intrinsics have already been implemented in Rust (for all architectures).

Did you link to the compiler_builtins crate? You need to have `extern crate compiler_builtins` somewhere in your dependency graph (not just in a Cargo.toml). (For some reason people tend to forget to do that -- I have received several reports like this. I'm wondering if this is a documentation problem or something else)

**Comment by SergioBenitez** [comment]
@japaric You're 100% correct; what a silly mistake! It might be worth mentioning this in https://github.com/japaric/xargo#creating-a-sysroot-with-custom-crates. Perhaps part of the confusion comes from being able to list `core` as a dependency in `Xargo.toml` without an `extern crate core;`.

**Comment by japaric** [comment]
I don't think that's a particularly good example because `steed` already contains a `extern crate compiler_builtins` but I have added a new bullet to the caveats / gotchas section to note that sysroot crates, other than core and std, need to be explicitly linked (`extern crate`-ed).

Thanks for the input, @SergioBenitez!
