### ISSUE TITLE
definition of an unknown language item

### ISSUE THREAD

**Issue by pittma** [rust-lang-nursery/compiler-builtins#214]
Hi all :wave:

I'm x-compiling for 32-bit Arm-7a, and I see `definition of an unknown language item` for all of the 128-bit functions in `int/shift.rs`:

```
# ...
error[E0522]: definition of an unknown language item: `u128_shro`.
   --> /home/dpitt/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/200c94e/src/int/shift.rs:129:1
    |
129 | / pub fn rust_u128_shro(a: u128, b: u128) -> (u128, bool) {
130 | |     (rust_u128_shr(a, b as _), b >= 128)
131 | | }
    | |_^

error[E0522]: definition of an unknown language item: `u128_div`.
   --> /home/dpitt/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/200c94e/src/int/udiv.rs:274:1
    |
274 | / pub fn rust_u128_div(a: u128, b: u128) -> u128 {
275 | |     __udivti3(a, b)
276 | | }
    | |_^

error[E0522]: definition of an unknown language item: `u128_rem`.
   --> /home/dpitt/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/200c94e/src/int/udiv.rs:278:1
    |
278 | / pub fn rust_u128_rem(a: u128, b: u128) -> u128 {
279 | |     __umodti3(a, b)
280 | | }
    | |_^

error: aborting due to 24 previous errors

error: Could not compile `compiler_builtins`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

It looks like these types were added only about a [week ago](https://github.com/rust-lang-nursery/compiler-builtins/commit/60d949ba1d10bf9d3dd940c3307d82d6f2d33c8b); when I back up to [before this commit](https://github.com/rust-lang-nursery/compiler-builtins/commit/02b3734a5ba6de984eb5a02c50860cc014e58d56), all is copacetic.

I'm using nightly:
```shell
$ rustc -V     
rustc 1.23.0-nightly (bd0e45a32 2017-11-06)
```

And here's the target I'm using to build: https://gitlab.com/robigalia/sel4-targets/blob/master/arm-sel4-robigalia.json

Let me know if there's any other information I can provide that would be helpful, and thanks!

**Comment by japaric** [comment]
> /home/dpitt/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/200c94e/src/int/shift.rs:129:1

You are using the git version of compiler-builtins which may not be compatible with the Rust compiler you are using (because of lang items and etc.). I'd suggest using the snapshot shipped in the rust-src component -- that one is guaranteed to work with your current toolchain.

I don't know what you are using to compile compiler-builtins but if you are using Xargo you would need to change the Xargo.toml file to this:

``` toml
# Xargo.toml
[dependencies.core]
stage = 0

[dependencies.compiler_builtins]
features = ["mem"]
stage = 1
```

If you are specifying compiler-builtins in Cargo.toml then you'll need to change the Cargo .toml to look like this:

``` toml
# Cargo.toml
# ... omitted other stuff ...

[dependencies.compiler_builtins]
path = "/home/japaric/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcompiler_builtins"
```

where `/home/japaric/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu` should be replaced with the output of the command `rustc --print sysroot`.

**Comment by pittma** [comment]
Hi @japaric, and sorry for the immense delay.

You are absolutely right, and adding `compiler_builtins` to my xargo.toml file did the trick.  Thanks for your help!

Is this documented somewhere? And if not, I'd be happy to add it to documentation, I just may need a pointer to where to deposit it.

Thanks again!

**Comment by japaric** [comment]
> Is this documented somewhere? 

I think the problem may be that some existing documentation is suggesting using `git` versions for the sysroot crates. What prompted you to try the `git` version of `compiler_builtins`? Documentation should suggest using "versionless" (no `path` or `git`) dependencies in Xargo.toml; those map to the source in the rust-src component.

I see there's a mention of compiler_builtins + git in the Xargo docs. I'll fix that one to use the versionless dependency.
