### ISSUE TITLE
Question: whose responsibility is it to provide builtins used by C code?

### ISSUE THREAD

**Issue by parched** [rust-lang-nursery/compiler-builtins#217]
If you link some C code into your rust executable (e.g., libc) and that code uses some builtins that aren't needed by Rust (e.g., long double builtins), whose responsibility is it to provide them? This crate or something else?

In other words, should this crate provide C builtins or, if the target is linker_flavour is gcc or ld, should libgcc be added to the list of things linked?

CC @alexcrichton @japaric 

Related https://github.com/rust-lang-nursery/compiler-builtins/issues/201

**Comment by alexcrichton** [comment]
I'd personally expect these to come from libgcc, not compiler-builtins. This crate is in general targeted only at Rust's needs, not C's.

**Comment by Amanieu** [comment]
In the case of #201, the musl libc is shipped as part of the compiler. In that case it should be the responsibility of the compiler to provide the necessary symbols for linking the provided libc. I agree with alex though, this should be done by linking in libgcc or libcompiler-rt.

**Comment by parched** [comment]
Ok, so rustc should add libgcc to the linker commandline for all targets that use gcc or ld linker flavor?

What happens when someone wants to use compiler-rt instead, do we add a flag to rustc allowing the user to specify the c-builtins library, if and when that is needed?

**Comment by alexcrichton** [comment]
I don't personally think that rustc should do this, but rather a user should explicitly request libgcc.

**Comment by parched** [comment]
@alexcrichton Do you mean via `#[link(name = gcc)]` or `RUSTFLAGS`? It's really just a coincidence that every (std) rust executable doesn't need libgcc because all the libcs support long double.

**Comment by alexcrichton** [comment]
Yeah that's what I'd personally expect.

**Comment by Amanieu** [comment]
An alternative could be to add the `libgcc` dependency to the `libc` crate.

**Comment by Amanieu** [comment]
I think this is resolved by https://github.com/rust-lang/libc/pull/1034.

We will link to libgcc when we provide a statically linked libc as part of the libc crate (musl), but otherwise leave it to the dynamic linker to find `libgcc.so` if it is required by `libc.so`.

**Comment by alexcrichton** [comment]
👍
