### ISSUE TITLE
Has Rust recently updated to an LLVM which emits calls to clzsi2?

### ISSUE THREAD

**Issue by ketsuban** [rust-lang-nursery/compiler-builtins#260]
According to the README, LLVM never emits calls to `__clzsi2`. However, when compiling my code targeting the Game Boy Advance (`thumbv4-none-eabi`) with a recent nightly (`rustc 1.30.0-nightly (0198a1ea4 2018-09-08)`) compiler-builtins is built with calls to `__clzsi2` in many functions, leading to undefined references at link time.

Here's my target file on the offchance that's relevant.

```json
{
    "abi-blacklist": [
        "stdcall",
        "fastcall",
        "vectorcall",
        "thiscall",
        "win64",
        "sysv64"
    ],
    "ar": "arm-none-eabi-ar",
    "arch": "arm",
    "atomic-cas": false,
    "data-layout": "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64",
    "emit-debug-gdb-scripts": false,
    "env": "",
    "executables": true,
    "features": "+soft-float,+strict-align",
    "linker": "arm-none-eabi-gcc",
    "linker-flavor": "gcc",
    "llvm-target": "thumbv4-none-eabi",
    "os": "none",
    "panic-strategy": "abort",
    "pre-link-args": {
        "gcc": [
            "--specs=gba.specs"
        ]
    },
    "relocation-model": "static",
    "target-c-int-width": "32",
    "target-endian": "little",
    "target-pointer-width": "32",
    "vendor": ""
}
```

It presupposes a [devkitARM](https://devkitpro.org/) toolchain is available.

**Comment by alexcrichton** [comment]
Thanks for the report! It probably is the case yeah that LLVM has changed from when the README was written to now. We can certainly implement this function!

**Comment by Lokathor** [comment]
@alexcrichton the relevant function is fairly simple

```rust
#[no_mangle]
pub unsafe extern "C" fn __clzsi2(mut x: usize) -> usize {
  let mut y: usize;
  let mut n: usize = 32;
  y = x >> 16;
  if y != 0 {
    n = n - 16;
    x = y;
  }
  y = x >> 8;
  if y != 0 {
    n = n - 8;
    x = y;
  }
  y = x >> 4;
  if y != 0 {
    n = n - 4;
    x = y;
  }
  y = x >> 2;
  if y != 0 {
    n = n - 2;
    x = y;
  }
  y = x >> 1;
  if y != 0 {
    n - 2
  } else {
    n - x
  }
}
```

Should I just put in a PR for this or is there some additional process needed for adding new builtins?

**Comment by alexcrichton** [comment]
@Lokathor nah that'd be great to add! It can be hooked up to the test suite we already have to verify correctness as well

**Comment by Lokathor** [comment]
I have another PR waiting, but once it's in I'll get to this one done up.

**Comment by Lokathor** [comment]
https://github.com/rust-lang-nursery/compiler-builtins/pull/267 is merged
