### ISSUE TITLE
Need a x32 stack probing function 

### ISSUE THREAD

**Issue by crlf0710** [rust-lang-nursery/compiler-builtins#282]
According to https://github.com/rust-lang/rust/issues/59674, such a function is needed to re-enable stack probing on gnux32 in [src/probestack.rs](https://github.com/rust-lang-nursery/compiler-builtins/blob/master/src/probestack.rs).

**Comment by nikic** [comment]
x32 stack probing is now reenabled using the probing function for x86_64. I don't think a separate one is needed.

**Comment by crlf0710** [comment]
Yeah, just need to wait for https://github.com/rust-lang/rust/pull/62808 to land, then we can close this.

**Comment by nikic** [comment]
Oh sorry, I thought that had already landed after seeing the "merged" message ... but apparently that didn't actually happen.

**Comment by bjorn3** [comment]
Actually it is merged into master:

![afbeelding](https://user-images.githubusercontent.com/17426603/61803223-12e36100-ae32-11e9-9911-cd43b6af4278.png)

**Comment by nikic** [comment]
I've manually closed that PR now and it properly went into "merged" state. Github just went a bit crazy...

**Comment by crlf0710** [comment]
ok, then let's close this too.
