### ISSUE TITLE
Should `rustc-dep-of-std` feature really depend on `c`?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang-nursery/compiler-builtins#288]
It used to be possible to almost entirely build libstd for some target without having a C toolchain (the "almost" being due to https://github.com/rust-lang/rust/issues/56443: in the final step, a dylib gets built). To do this, we have to be careful to not enable the `c` feature of compiler-builtins. This could be achieved by disabling the default features of libstd.
However, that regressed when compiler-builtins got moved out of the workspace; now liballoc depends on the `rustc-dep-of-std` feature (curiously, libstd does not), and that feature depends on the `c` feature.

Is it really necessary that the `rustc-dep-of-std` feature depends on `c`?

**Comment by alexcrichton** [comment]
It isn't, just needs to be enabled somehow and that can be done with a feature of std instead of an implicit feature enabled by rustc-dep-of-std

**Comment by RalfJung** [comment]
libstd [enables it per default](https://github.com/rust-lang/rust/blob/80e7cde2238e837a9d6a240af9a3253f469bb2cf/src/libstd/Cargo.toml#L52).

So, does that mean we can remove it from `rustc-dep-of-std`?

**Comment by alexcrichton** [comment]
So long as libstd builds and uses the `c` feature for released builds I don't have a personal preference how this is all architected.
