### ISSUE TITLE
bcmp missing

### ISSUE THREAD

**Issue by jethrogb** [rust-lang-nursery/compiler-builtins#303]
[LLVM 9](https://github.com/rust-lang/rust/pull/62592) emits calls to `bcmp`:
```
  = note: rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-fortanix-unknown-sgx/lib/libtest-a9ecdf8e579fd5d7.rlib(test-a9ecdf8e579fd5d7.test.bolfc4sh-cgu.0.rcgu.o):test.bolfc4sh-cgu.0:function _$LT$test..TestDesc$u20$as$u20$core..cmp..PartialEq$GT$::eq::h29076b407d2a6562: error: undefined reference to 'bcmp'
          collect2: error: ld returned 1 exit status
```

**Comment by jethrogb** [comment]
bcmp: This function is deprecated (marked as LEGACY in POSIX.1-2001): use memcmp(3) in new programs.  POSIX.1-2008 removes the specification of bcmp().

**Comment by alexcrichton** [comment]
Looks like this is going to be handled in https://github.com/rust-lang/rust/pull/62698
