### ISSUE TITLE
Trim the list of fallbacks in compiler-rt

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/compiler-builtins#78]
Added in https://github.com/japaric/rustc-builtins/pull/74, the `c` feature enables building a bunch of compiler-rt intrinsics.

Right now the list is [pretty huge](https://github.com/japaric/rustc-builtins/blob/61484acb3aa661f424ecc86ce39b9ced8fcfb268/build.rs#L102-L406) and I think we definitely don't need a good number of these like:
- `emutls.c`
- `gcc_personality_v0.c`

etc

It looks like there's [already a list](https://github.com/japaric/rustc-builtins/#unimplemented-functions) of crossed off functions, maybe those could all be excluded?

**Comment by adlerd** [comment]
Worse, some of the included files depend on other, nonincluded files (not always explicitly; sometimes via intrinsics themselves, it seems).

For example, enabling feature "c" targeting aarch64 results in
> $HOME/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/0507842/./compiler-rt/compiler-rt-cdylib/compiler-rt/lib/builtins/mulxc3.c:71: undefined reference to `__multf3'

among a dozen other link errors.

**Comment by alexcrichton** [comment]
I think this is effectively done now, we've got lots of testing for duplicate symbols and the list is getting smaller, so closing.
