### ISSUE TITLE
Floating point add gives different results than compiler-rt on arm-unknown-linux-gnueabi

### ISSUE THREAD

**Issue by mattico** [rust-lang-nursery/compiler-builtins#90]
I'm still trying to figure out what was wrong with #48, and I'd like another pair of eyes on this because I have no idea what is going on.

I added an implementation of `arbitrary_float!` again, and [ran the tests](https://travis-ci.org/mattico/rustc-builtins/builds/164723455). Only [the arm-unknown-linux-gnueabi target](https://travis-ci.org/mattico/rustc-builtins/jobs/164723458#L811) failed. So I grab the arguments that made the test fail and [put them into a regular test](https://github.com/mattico/rustc-builtins/commit/1dd0832a952d2f80ef273cb819b106f1553bc431). On the next build, [the test passes](https://travis-ci.org/mattico/rustc-builtins/jobs/164727780#L784) because we're actually getting the [right answer](https://www.wolframalpha.com/input/?i=0.000000000000000000000000000000000000011540496-0.00000000000000000000000000000000000000359621) in this case. It's gcc_s and compiler-rt that have the wrong answer.

Either:
1. There's some subtle bug in the test infrastructure
2. gcc_s and libcompiler-rt both have the same bug but we don't despite the code being almost identical to compiler-rt
3. QEMU is broken but only in this specific way
4. The C compiler's optimizations cause rounding in very small numbers, but rustc does not
5. Something else?

**Comment by mattico** [comment]
New theory: compiler-rt and gcc_s are both compiled with optimizations, we are not (during tests). The optimizer moves/combines some operations which leads to subtle rounding differences in very small numbers.

**Comment by alexcrichton** [comment]
Oh that's actually a really good point that we should always compile compiler-rt with optimizations. Right now compiler-rt is conditionally optimized, but gcc_s is pulled in from the system so I think that's always optimize.

**Comment by japaric** [comment]
> The C compiler's optimizations cause rounding in very small numbers, but rustc does not

Do the errors go away if you test with optimizations enabled (`cargo test --release`)?

Are these roundings, `-ffast-math` optimizations? Who's doing the rounding (less precision) C or Rust?

> we should always compile compiler-rt with optimizations.

This should be a simple change in the build.rs via gcc::Config (I expect)

But ... enabling optimizations shouldn't change the results of the compiler-rt intrinsics, right? That doesn't sound quite right. You should get the same output regardless of the optimization level.

**Comment by mattico** [comment]
> Do the errors go away if you test with optimizations enabled (cargo test --release)?
> Are these roundings, -ffast-math optimizations? Who's doing the rounding (less precision) C or Rust?

No, release builds don't change our results. Our answer agrees with wolfram alpha which uses arbitrary precision arithmetic so it seems like `compiler-rt` and `gcc_s` have the wrong answer in this case.

I feel like I was a bit unclear about this so here is a table:

Answers for 1.1540496e-38 + -3.59621e-39 on *arm-unknown-linux-gnueabi*

Method | Answer
-------|------
Wolfram Alpha|**7.944286e-39**
Rust Constant Folding|**7.944286e-39**
rustc-builtins|**7.944286e-39**
gcc_s|4.133629e-39
compiler-rt|4.133629e-39

The `check!` test gives answers for rustc-builtins, gcc_s, and compiler-rt and the `#[test]` test is probably using constant folding.

I think it's still possible that gcc is less strict about reordering or combining float operations than rust/llvm, but [this page](https://gcc.gnu.org/wiki/FloatingPointMath) makes it look like that only happens with non-standard flags so perhaps that is not the case.

I'm going to start looking at the disassembly since it doesn't seem like there's a simple answer.

**Comment by mattico** [comment]
Hmm. The Rust disassembly is much longer and uses many more registers than the C version. I was expecting them to be a bit more similar. I guess it's time to install IDA.

**Comment by mattico** [comment]
Compiling compiler-rt with clang gives an assembly output that is much more similar to the rust version. I'm going to see if it gives the same results.

**Comment by japaric** [comment]
> Compiling compiler-rt with clang gives an assembly output that is much more similar to the rust version.

That makes given that both clang and rust are based on LLVM.

This sounds like gcc has different defaults around rounding compared to LLVM.

> this page makes it look like that only happens with non-standard flags so perhaps that is not the case.

Perhaps try compiling compiler-rt using the "full IEEE 754 compliance" flags: -frounding-math -fsignaling-nans. It seems that gcc defaults to not being fully compliant with IEEE 754. I wonder if LLVM is fully compliant with IEEE 754 by default; that could be the difference.

**Comment by mattico** [comment]
Adding the flags didn't change anything.

**Comment by mattico** [comment]
I used a little C program to test the compiler-rt version of `__addsf3` when compiled with different compilers, but all of them give `7.944286e-39`.

**Comment by japaric** [comment]
> Adding the flags didn't change anything.
> I used a little C program to test the compiler-rt version of __addsf3 when compiled with different compilers, but all of them give 7.944286e-39.

:confused: 

So, uhmm, calling the same function from C vs from Rust produces different output? Could this be a calling convention problem? Seems unlikely though as you only get different outputs (between C and Rust) for a few inputs. The only other thing I can think about is side effects: it's possible to change the rounding mode using [`fesetround`](http://stackoverflow.com/a/6867722); perhaps, some pre-main/initialization code is setting that in different ways for C vs for Rust.

**Comment by mattico** [comment]
@japaric Yeah I agree it's a bit strange... I'm still investigating.

Here's a rough summary of what I did (from memory):

```
$ arm-linux-gnueabi-gcc -O2 -fno-builtins -c addsf3.c # from compiler-rt
$ cat test_arm.c
#include <stdio.h>
extern float __addsf3(float, float);
int main() {
    printf("%e\n", __addsf3(1.1540496e-38, -3.59621e-39));
    return 0;
}
$ arm-linux-gnueabi-gcc -fno-builtins test_arm.c addsf3.o -o test_arm_gcc
$ ./test_arm_gcc # runs in qemu...
```
And I did the equivalent for clang as well.

I'll look into the crt initialization stuff to see if they mess with floating point rounding.

I guess I should also make an equivalent rust program, which should tell us if the error only happens inside our `check!` tests for whatever reason.

**Comment by mattico** [comment]
https://github.com/rust-lang/compiler-rt/pull/26#issuecomment-259751998

**Comment by mattico** [comment]
I'm currently looking into two possible theories:

1. japaric suggested a while ago that this is caused by undefined behaviour in compiler-rt (and gcc_s presumably) in floatsisf. I ran the test with the updated compiler-rt which is supposed to fix this issue and nothing changed, but I may have forgotten something. I'm in the process of porting floatsisf anyway.
2. https://github.com/rust-lang/compiler-rt/pull/26#issuecomment-259751998 above has to do with arm calling conventions so that possibly applies here. There may be some other calling convention issue as well.

**Comment by parched** [comment]
@mattico I don't think 2. will be the issue as that only affects hard float.

**Comment by ithinuel** [comment]
I don't know if it may be related to this but i noticed that when the test starts running, QEMU complains about `qemu: Unsupported syscall: 384`.

**Comment by japaric** [comment]
@ithinuel I see that all the time when running Rust programs compiled for ARM under QEMU. Never bothered investigating but it hasn't been an issue with programs that don't do (too many) floating point operations.

**Comment by Amanieu** [comment]
That's the `getrandom` system call, but having it unsupported isn't a big problem since the code just falls back to `/dev/urandom`.

**Comment by japaric** [comment]
So, using a recent nightly, I tested changing the intrinsics that involve floating point arguments/return values from `extern "C"` to `extern "aapcs"` but that didn't fix these tests; I still see the same errors on both gnueabi and gnueabihf.

**Comment by Amanieu** [comment]
@japaric Did you change the ABI for the `extern` block in `compiler-builtins/compiler-rt/compiler-rt-cdylib/src/lib.rs`? On ARM, *all* of the intrinsics use the `aapcs` soft-float calling convention.

**Comment by japaric** [comment]
@Amanieu No, I didn't because those functions get immediately turned into `usize`s so I think the CC they are declared with matters.

> On ARM, all of the intrinsics use the aapcs soft-float calling convention.

I only tested changing the calling convention of addsf3 and adddf3 as those are the only intrinsics that are causing problems. Here are my changes: https://gist.github.com/japaric/13755ba481a6cd1199fd07f2f32d8c1e

**Comment by Amanieu** [comment]
@japaric This line should use "aapcs" instead of "C":
```
-            fn $name($f: extern fn($($farg),*) -> $fret,
+            fn $name($f: extern "C" fn($($farg),*) -> $fret,
```
